language: node_js
node_js:
  - '8'

branches:
  only:
    - master

cache:
  directories:
    - node_modules
    - client/node_modules

install:
  - npm install
  - NPM_CONFIG_PRODUCTION=false npm install --prefix client && npm run build --prefix client

deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api-key:
    secure: $HEROKU_API_KEY
  app: emaily-node-with-react
