language: node_js
node_js:
  - '8'
sudo: false

branches:
  only:
    - master

cache:
  directories:
    - node_modules
    - client/node_modules

install:
  - npm install
  - npm install --perfix client
  - npm run build --prefix client

deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api-key:
    secure: $HEROKU_API_KEY
  app: emaily-node-with-react
